###Register user
POST http://localhost:4700/user/register
Content-Type: application/json 

{
   "userName":"Sawud",
   "userPhone":"07546326421",
   "userEmail":"dawud@gmail.com",
   "userPassword":"12345678"
}


###LOGIN USER 
POST http://localhost:4700/user/login
Content-Type: application/json 

{
   "userName":"Sawud",
   "userPassword":"12345678"
}