###Register user
POST http://localhost:4700/user/register
Content-Type: application/json 

{
   "userName":"David Munyiri",
   "userPhone":"1750505060",
   "userEmail":"munyiri@gmail.com",
   "userPassword":"12345678"
}


###LOGIN USER 
POST http://localhost:4700/user/login
Content-Type: application/json 

{
   "userName":"David Munyiri",
   "userPassword":"12345678"
}