###Register user
POST http://localhost:4700/user/register
Content-Type: application/json 

{
   "userName":"Abdul Mwangi",
   "userPhone":"971712131",
   "userEmail":"davidmwangi@outlook.com",
   "userPassword":"12345678"
   
}


###LOGIN USER 
POST http://localhost:4700/user/login
Content-Type: application/json 

{
   "userEmail":"davidmwangi@outlook.com",
   "userPassword":"12345678"
}



###Update user details, You use user Details to update his details
PUT http://localhost:4700/user/update/
Content-Type: application/json 

{
   "userName":"John wachira",
   "userPhone":"887876632",
   "userEmail":"abdulahi@gmail.com",
   "userPassword":"12345678"
}

###Add product
POST http://localhost:4700/product/add 
Content-Type: application/json 

{
    "productName":"JBL Woofer",
    "productDescription":"A 50V heater",
    "productClassification":"systems",
    "productCategory":"Cars",
    "productCost":"27000",
    "earlyCost":"28000",
    "productImg":"https://tv"
}



###Update product ,YOU use productId to update its details
PUT http://localhost:4700/product/update/
Content-Type: application/json 

{
    "productName":"Kenyan Sugar",
    "productDescription":"A Kabras product",
    "productClassification":"Groceries",
    "productCategory":"Kitchenries",
    "productCost":"520",
    "earlyCost":"570",
    "productImg":"https://sugar/product"
}


###view One product
GET http://localhost:4700/product/viewOneProduct/fba2ebd1-12e2-4771-ad71-762f1ffd5eb9 


###VIEW ALL Products
GET http://localhost:4700/product/allProducts/Shoes


###delete product
DELETE http://localhost:4700/product/delete/68550b53-4ed4-45b1-8fec-1e447c0daa4b


 
###ADD PRODUCT TO CART 
POST http://localhost:4700/cart/add 
Content-Type: application/json 

{
    "productName":"Heater",
    "productCost":"21000",
    "productImg":"https://tv",
    "boughtBy":"dbdefa10-9141-454f-b4f8-8c527c1ec361"
}


###VIEW CART , You use UserId to view Cart
GET http://localhost:4700/cart/viewCart/dbdefa10-9141-454f-b4f8-8c527c1ec361 


###ClearAll Product from cart, You use UserId clear all cart
DELETE http://localhost:4700/cart/deleteAll/dbdefa10-9141-454f-b4f8-8c527c1ec361 

###Remove one item from the cart ,You use productId to remove one item from the cart
DELETE http://localhost:4700/cart/removeOne/4f7768ea-aeda-4db9-b035-4cd16babb84d 


###reset password request
POST http://localhost:4700/reset/reset-password
Content-Type: application/json 

{
   "userEmail":"davidmunyiri2019@outlook.com"
}



###reseting using token
POST http://localhost:4700/reset/reset-password/FB70E4
Content-Type: application/json 

{
   "newPassword":"23456789"
}
